KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KMART_CRUD_MVC_Examen.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Tienda> Stock{ get; set; }
    }
}

KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Models/ErrorViewModel.cs
using System;

namespace KMART_CRUD_MVC_Examen.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Models/Tienda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KMART_CRUD_MVC_Examen.Models
{
    public class Tienda
    {
        [Key]
        public int KId { get; set; }

        [Required(ErrorMessage = "Ingresa el nombre del producto")]
        [Display(Name = "Nombre del producto")]
        public string KProd { get; set; }

        [Required(ErrorMessage = "Ingresa una descripcion del producto")]
        [Display(Name = "Descripcion")]
        public string KDesc { get; set; }

        [Required(ErrorMessage = "Ingresa el numero de unidades en Inventario")]
        [Display(Name = "Inventario")]
        [Range(1, 1000)]
        public int KStock { get; set; }

        [Required(ErrorMessage = "Ingresa un precio")]
        [Display(Name = "Precio")]
        public decimal KPrice { get; set; }


        [Required(ErrorMessage = "Ingresa un codigo de producto valido")]
        [Display(Name = "Codigo")]
        public string KCode { get; set; }
    }
}

KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KMART_CRUD_MVC_Examen.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KMART_CRUD_MVC_Examen.Controllers
{
    public class TiendaController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TiendaController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {

            var displaydata = _db.Stock.ToList();
            return View(displaydata);
        }

        [HttpGet]

        public async Task<IActionResult> Index(String prodSearch)

        {
            ViewData["GetProductDetails"] = prodSearch;
            var productquery = from x in _db.Stock select x;
            if (!String.IsNullOrEmpty(prodSearch))
            {
                productquery = productquery.Where(x => x.KProd.Contains(prodSearch) || x.KCode.Contains(prodSearch));

            }
            return View(await productquery.AsNoTracking().ToListAsync());

        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Tienda nPr)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nPr);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return View(nPr);

        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }
            var getProductDetail = await _db.Stock.FindAsync(id);
            return View(getProductDetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }
            var getProductDetail = await _db.Stock.FindAsync(id);
            return View(getProductDetail);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(Tienda vProduct)

        {
            if (ModelState.IsValid)
            {
                _db.Update(vProduct);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return View(vProduct);

        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getProductDetails = await _db.Stock.FindAsync(id);
            return View(getProductDetails);
        }

        [HttpPost]

        public async Task<IActionResult> Delete(int id)

        {
            var getProductDetail = await _db.Stock.FindAsync(id);
            _db.Stock.Remove(getProductDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");

        }


    }
}

KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KMART Stock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Tienda" asp-action="Index">KMART</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tienda" asp-action="Index">Pagina de Inicio</a>
                        </li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - KMART 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Views/Tienda/Create.cshtml
@model KMART_CRUD_MVC_Examen.Models.Tienda

@{
    ViewData["Title"] = "Create";
}

<h1>Ingresar Producto</h1>

<h4>Tienda</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="KProd" class="control-label"></label>
                <input asp-for="KProd" class="form-control" />
                <span asp-validation-for="KProd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KDesc" class="control-label"></label>
                <input asp-for="KDesc" class="form-control" />
                <span asp-validation-for="KDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KStock" class="control-label"></label>
                <input asp-for="KStock" class="form-control" />
                <span asp-validation-for="KStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KPrice" class="control-label"></label>
                <input asp-for="KPrice" class="form-control" />
                <span asp-validation-for="KPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KCode" class="control-label"></label>
                <input asp-for="KCode" class="form-control" />
                <span asp-validation-for="KCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ingresar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Views/Tienda/Delete.cshtml
@model KMART_CRUD_MVC_Examen.Models.Tienda

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar producto</h1>

<h3>Estas seguro que deseas eliminar eñ producto?</h3>
<div>
    <h4>Tienda</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KProd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KProd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KStock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar a la lista</a>
    </form>
</div>

KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Views/Tienda/Detail.cshtml
@model KMART_CRUD_MVC_Examen.Models.Tienda

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles del producto</h1>

<div>
    <h4>Tienda</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KProd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KProd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KStock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KCode)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Regresar a la lista</a>
</div>

KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Views/Tienda/Edit.cshtml
@model KMART_CRUD_MVC_Examen.Models.Tienda

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Producto</h1>

<h4>Tienda</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KId" class="control-label"></label>
                <input asp-for="KId" class="form-control" />
                <span asp-validation-for="KId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KProd" class="control-label"></label>
                <input asp-for="KProd" class="form-control" />
                <span asp-validation-for="KProd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KDesc" class="control-label"></label>
                <input asp-for="KDesc" class="form-control" />
                <span asp-validation-for="KDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KStock" class="control-label"></label>
                <input asp-for="KStock" class="form-control" />
                <span asp-validation-for="KStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KPrice" class="control-label"></label>
                <input asp-for="KPrice" class="form-control" />
                <span asp-validation-for="KPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KCode" class="control-label"></label>
                <input asp-for="KCode" class="form-control" />
                <span asp-validation-for="KCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KMART_CRUD_MVC_Examen/KMART_CRUD_MVC_Examen/Views/Tienda/Index.cshtml
@model IEnumerable<KMART_CRUD_MVC_Examen.Models.Tienda>

@{
    ViewData["Title"] = "Index";
}
    
        <h1>Pagina de Inventario</h1>
        

            <p>
                <a asp-action="Create">Agregar Nuevo Producto</a>
            </p>

            <form asp-action="Index" method="get">

                <p>
                    <input type="search" placeholder="Ingresa Nombre o Codigo del producto:" name="prodSearch"
                           value="@ViewData["GetProductDetails"]" style="width = 1500px;" />
                    <input type="submit" value="Buscar" class="btn btn-primary" />
                    <a asp-action="Index">Ver todos los productos</a>
                </p>

            </form>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.KId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.KProd)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.KDesc)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.KStock)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.KPrice)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.KCode)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.KId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.KProd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.KDesc)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.KStock)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.KPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.KCode)
                            </td>
                            <td>
                                @Html.ActionLink("Editar", "Edit", new { id = item.KId }, new { @class = "btn btn-primary" }) |
                                @Html.ActionLink("Detalles", "Detail", new { id = item.KId }, new { @class = "btn btn-success" }) |
                                @Html.ActionLink("Eliminar", "Delete", new { id = item.KId }, new { @class = "btn btn-danger" })
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
      